

This will be a 16 hour lecture course on the theory and applications
of deep learning.  All lectures should be recorded automatically and
available shortly afterwards through the class
[[https://www.vle.cam.ac.uk/course/view.php?id=253240][moodle]]. The videos are also directly available via [[https://cambridgelectures.cloud.panopto.eu/Panopto/Pages/Sessions/List.aspx#folderID=%22eebe74af-1f79-4901-a142-b08c008c499e%22][Panopto]].


** Consent for recordings

Live lectures will be recorded, and we assume that if you have your
camera or microphone on, then you consent to being recorded.  If you
wish to revoke your consent, please contact us and we will need to
edit you out of the recording.

* Lectures

** Lecture 01, 02

[2023-10-26 Thu 09:00-11:00]

[[file:slides/intro.pdf][Introduction]]

[[file:slides/neuro101.pdf][Neuro 101]]

** Lecture 03, 04

[2023-10-30 Mon 09:00-11:00]

[[file:slides/perceptron.pdf][Perceptron]]

[[file:slides/backprop.pdf][Back propagation]]

[[file:slides/backprop2.pdf][extra handout]]


** Lecture 05, 06

[2023-11-02 Thu 09:00-11:00]

Back propagation continued; derivation.

** Lecture 07, 08

[2022-11-07 Mon 09:00-11:00]

[[file:slides/dimred.pdf][Dimensionality reduction]]

[[file:slides/tips.pdf][Tips and tricks]]


** Lecture 09, 10

[2023-11-09 Thu 09:00-11:00]

Autograd

[[file:slides/images.pdf][Images]]


**  Lecture 11, 12

[2022-11-14 Mon 09:00-11:00]


Images ctd.

[[file:slides/hopfield.pdf][Hopfield]]

[[file:slides/sequences.pdf][Sequences]] (part 1)

** Lecture 13, 14

Sequences  (part 2)

Transformers

[2023-11-16 Thu 09:00-11:00]

<https://arxiv.org/abs/2304.10557>

** Lecture 15, 16

[[file:slides/rl.pdf][RL]]
[2023-11-20 Mon 09:00-11:00]


* Practical on 'Computational neuroscience modelling'

This optional session will be 1-3pm on Friday 10th November in MR15.

* Reading

Most of the lectures will mention key papers to read.  A good
introductory text is [[https://jamesstone.sites.sheffield.ac.uk/books/artificial-intelligence-engines][AI Engines: mathematics of deep learning]] by
Dr James V Stone.

* Assignment


One assignment to be set at the end of the course; due in start of
Lent Term 2024.

[[dla1_2023.pdf][Assignment one]]

See <https://github.com/sje30/dl2023/wiki> for questions and comments
on the assignment.  If you have a question ahead of the feedback
session on 7th December (10am, zoom), please email me.



